Algoritmo "impar ou par"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : Cristiane
// Descrição   : Verificar se o número digitado é impar ou par
// Autor(a)    : Webster Roberto Siqueira Santos
// Data atual  : 09/09/2022

Var
x : real


Inicio
escreva("Escreva um número: ")
leia(x)

se x%2=0 entao
   escreva("O número é par")
senao
   escreval("O número é ímpar")
fimse


Fimalgoritmo