Algoritmo "reoita ate x =10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/11/2022
Var
// Seção de Declarações das variáveis 
x: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 x <-1
repita
escreval(x)
x <-x + 1
ate (x > 10)


Fimalgoritmo