Algoritmo "teste enquanto"

Var
// Seção de Declarações das variáveis 
 x, soma :inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Digite o primeiro número: ")
leia (x)
     soma <- 0
     enquanto x <> 0 faca
     soma <- soma + x
     escreva ("digite outro número: ")
     leia (x)
     
     fimenquanto
     
     escreval ("Soma = ", soma)

Fimalgoritmo